// Telegram bot phrases in Russian, Tajik and English.
import type { Lang } from "../i18n/locales";

const ru = {
  book: "✦ Записаться",
  my: "Мои записи",
  prices: "Цены",
  contacts: "Контакты и адрес",
  language: "🌐 Язык · Забон · Language",
  backToMenu: "← В меню",
  back: "← Назад",
  help: "Чем могу помочь?",
  startOver: "Давайте начнём сначала.",
  welcome: (name?: string) =>
    `Здравствуйте${name ? `, ${name}` : ""}! ✦\nЭто Mavzunai Jovid - Gallery of Beauty MJ, салон красоты и свадебный зал в Душанбе.\n\nЗдесь можно записаться к мастеру, посмотреть и перенести свои записи.`,
  onlyButtons: "Я понимаю кнопки ниже ✦ Если нужен живой ответ - напишите нам в WhatsApp или позвоните.",
  chooseLanguage: "Выберите язык:",
  languageSet: "Готово - теперь говорю по-русски ✦",
  whatToDo: "Что будем делать?",
  unavailable: "Эта услуга сейчас недоступна для записи.",
  whichMaster: (svc: string, price: string, min: number) => `${svc} · ${price} · ${min} мин\nК какому мастеру?`,
  anyMaster: "Любой мастер",
  anyFreeMaster: "любой свободный мастер",
  pickDayOff: "Выберите день (понедельник - выходной):",
  pickDay: "Выберите день:",
  otherDays: "Другие дни:",
  waitAsk: "Можем записать вас в лист ожидания: если кто-то отменит запись на этот день, бот сразу пришлёт свободное время.",
  waitBtn: "🔔 Сообщить, если освободится",
  waitJoined: (day: string) => `Готово! Вы в листе ожидания на ${day}. Как только время освободится, пришлём сообщение - оно будет держаться за вами 30 минут.`,
  waitAlready: "Вы уже в листе ожидания на этот день - напишем, когда время освободится.",
  waitOffered: "Хорошие новости: подходящее время уже есть! Сейчас пришлём ссылку - подтвердите в течение 30 минут.",
  noTimeThatDay: (day: string) => `${day} - свободного времени нет. Выберите другой день:`,
  freeTimes: (day: string) => `Свободное время, ${day}:`,
  otherDay: "← Другой день",
  check: (s: { service: string; when: string; master: string; price: string; name: string; phone: string }) =>
    `Проверьте, пожалуйста:\n\n${s.service}\n${s.when}\nМастер: ${s.master}\nСтоимость: ${s.price}\n\nИмя: ${s.name}\nТелефон: ${s.phone}`,
  confirm: "✓ Записаться",
  otherTime: "Другое время",
  cancelFlow: "Отмена",
  askPhone: "Поделитесь, пожалуйста, номером телефона - кнопкой ниже или напишите его сообщением (например, 98 103 11 11).",
  sharePhone: "📱 Поделиться номером",
  badPhone: "Не получилось распознать номер. Нужно 9 цифр, например 98 103 11 11.",
  thanksKnown: (name: string) => `Спасибо, ${name}! Узнала вас ✦`,
  thanks: "Спасибо!",
  noBookingsForPhone: "По этому номеру записей пока нет.",
  askName: "Как к вам обращаться?",
  nameAgain: "Напишите, пожалуйста, ваше имя.",
  noUpcoming: "У вас нет предстоящих записей.",
  booking: (b: { service: string; when: string; master: string; confirmed: boolean }) =>
    `${b.service}\n${b.when} · мастер ${b.master}\n${b.confirmed ? "Подтверждено ✓" : "Ждёт подтверждения администратора"}`,
  move: "Перенести",
  cancel: "Отменить",
  anythingElse: "Что-нибудь ещё?",
  booked: (s: { service: string; when: string; master: string }) =>
    `Вы записаны ✦\n\n${s.service}\n${s.when}\nМастер: ${s.master}\n\nАдминистратор подтвердит запись. Напомним за день и за 2 часа до визита.`,
  bookedDeposit: (s: { service: string; when: string; master: string }) => `Время за вами ✦\n\n${s.service}\n${s.when}\nМастер: ${s.master}`,
  depositLink: (sum: string, time: string, url: string) => `Для этой услуги нужна предоплата ${sum}. Оплатите до ${time}, иначе время освободится:\n${url}`,
  payDeposit: (sum: string) => `💳 Внести предоплату ${sum}`,
  bonusBtn: "🎁 Бонусы",
  offersBtn: "✦ Акции",
  bonusInfo: (b: { balance: number; tier: string; percent: number; maxSpendPercent: number }) =>
    `У вас ${b.balance} бонусов ✦\nУровень «${b.tier}» - ${b.percent}% бонусами с каждого визита.\n\n1 бонус = 1 сомони. Бонусами можно оплатить до ${b.maxSpendPercent}% визита - скажите администратору.`,
  bonusOff: "Бонусная программа сейчас не действует.",
  offersTitle: "Акции салона:",
  offerLine: (o: { title: string; description: string; label: string; until: string; code: string | null }) =>
    `${o.label} - ${o.title}${o.description ? `\n${o.description}` : ""}\nдо ${o.until}${o.code ? ` · промокод ${o.code}` : ""}`,
  noOffers: "Сейчас акций нет - загляните позже ✦",
  cancelAsk: "Точно отменить эту запись?",
  yesCancel: "Да, отменить",
  no: "Нет",
  cancelled: "Запись отменена. Будем рады видеть вас в другой день ✦",
  cancelFailed: "Не получилось отменить",
  cantMove: "Эту запись нельзя перенести - напишите нам.",
  moveTitle: (service: string, master: string) => `Перенос: ${service}, мастер ${master}.\nВыберите новый день:`,
  pickNewDay: "Выберите новый день:",
  moved: (s: { service: string; when: string; master: string }) => `Перенесли ✦\n${s.service}\n${s.when}\nМастер: ${s.master}`,
  pricesTitle: "Цены, сомони:",
  master: "Мастер",
  phone: "Телефон",
  staffOk: "Готово: этот чат будет получать уведомления ресепшена о новых записях, отменах и переносах.",
  staffBad: "Код не подошёл. Возьмите актуальный код в CMS → Интеграции.",
};

export type BotTexts = typeof ru;

const tg: BotTexts = {
  book: "✦ Сабт шудан",
  my: "Сабтҳои ман",
  prices: "Нархҳо",
  contacts: "Тамос ва суроға",
  language: "🌐 Язык · Забон · Language",
  backToMenu: "← Ба меню",
  back: "← Бозгашт",
  help: "Чӣ хизмат кунам?",
  startOver: "Биёед аз нав оғоз кунем.",
  welcome: (name) =>
    `Салом${name ? `, ${name}` : ""}! ✦\nИн Mavzunai Jovid - Gallery of Beauty MJ, салони зебоӣ ва толори тӯй дар Душанбе.\n\nДар ин ҷо метавонед ба усто сабт шавед, сабтҳои худро бинед ва ба вақти дигар гузаронед.`,
  onlyButtons: "Ман тугмаҳои поёнро мефаҳмам ✦ Агар ҷавоби зинда лозим бошад - ба мо дар WhatsApp нависед ё занг занед.",
  chooseLanguage: "Забонро интихоб кунед:",
  languageSet: "Тайёр - акнун бо забони тоҷикӣ ҳарф мезанам ✦",
  whatToDo: "Чӣ кор мекунем?",
  unavailable: "Ин хизматрасонӣ ҳоло барои сабт дастрас нест.",
  whichMaster: (svc, price, min) => `${svc} · ${price} · ${min} дақ\nБа кадом усто?`,
  anyMaster: "Ҳар усто",
  anyFreeMaster: "ҳар устои холӣ",
  pickDayOff: "Рӯзро интихоб кунед (душанбе - рӯзи истироҳат):",
  pickDay: "Рӯзро интихоб кунед:",
  otherDays: "Рӯзҳои дигар:",
  waitAsk: "Метавонем шуморо ба рӯйхати интизорӣ нависем: агар касе сабтро барои ин рӯз бекор кунад, бот фавран вақти холиро мефиристад.",
  waitBtn: "🔔 Хабар диҳед, агар холӣ шавад",
  waitJoined: (day) => `Тайёр! Шумо дар рӯйхати интизорӣ барои ${day} ҳастед. Вақте ки вақт холӣ шавад, паём мефиристем - он 30 дақиқа барои шумо нигоҳ дошта мешавад.`,
  waitAlready: "Шумо аллакай дар рӯйхати интизорӣ барои ин рӯз ҳастед - вақте ки вақт холӣ шавад, менависем.",
  waitOffered: "Хабари хуш: вақти мувофиқ аллакай ҳаст! Ҳозир пайванд мефиристем - дар давоми 30 дақиқа тасдиқ кунед.",
  noTimeThatDay: (day) => `${day} - вақти холӣ нест. Рӯзи дигарро интихоб кунед:`,
  freeTimes: (day) => `Вақти холӣ, ${day}:`,
  otherDay: "← Рӯзи дигар",
  check: (s) => `Лутфан санҷед:\n\n${s.service}\n${s.when}\nУсто: ${s.master}\nНарх: ${s.price}\n\nНом: ${s.name}\nТелефон: ${s.phone}`,
  confirm: "✓ Сабт шудан",
  otherTime: "Вақти дигар",
  cancelFlow: "Бекор",
  askPhone: "Лутфан рақами телефонро фиристед - бо тугмаи поён ё бо паём (масалан, 98 103 11 11).",
  sharePhone: "📱 Фиристодани рақам",
  badPhone: "Рақам шинохта нашуд. 9 рақам лозим аст, масалан 98 103 11 11.",
  thanksKnown: (name) => `Ташаккур, ${name}! Шуморо шинохтам ✦`,
  thanks: "Ташаккур!",
  noBookingsForPhone: "Бо ин рақам ҳоло сабт нест.",
  askName: "Ба шумо чӣ тавр муроҷиат кунем?",
  nameAgain: "Лутфан номатонро нависед.",
  noUpcoming: "Шумо сабти оянда надоред.",
  booking: (b) => `${b.service}\n${b.when} · усто ${b.master}\n${b.confirmed ? "Тасдиқ шуд ✓" : "Интизори тасдиқи маъмур"}`,
  move: "Гузаронидан",
  cancel: "Бекор кардан",
  anythingElse: "Боз чизе лозим аст?",
  booked: (s) => `Шумо сабт шудед ✦\n\n${s.service}\n${s.when}\nУсто: ${s.master}\n\nМаъмур сабтро тасдиқ мекунад. Як рӯз ва 2 соат пеш аз ташриф ёдрас мекунем.`,
  bookedDeposit: (s) => `Вақт барои шумо ✦\n\n${s.service}\n${s.when}\nУсто: ${s.master}`,
  depositLink: (sum, time, url) => `Барои ин хизматрасонӣ пешпардохти ${sum} лозим аст. То соати ${time} пардохт кунед, вагарна вақт озод мешавад:\n${url}`,
  payDeposit: (sum) => `💳 Пешпардохти ${sum}`,
  bonusBtn: "🎁 Бонусҳо",
  offersBtn: "✦ Аксияҳо",
  bonusInfo: (b) =>
    `Шумо ${b.balance} бонус доред ✦\nСатҳи «${b.tier}» - ${b.percent}% бо бонус аз ҳар ташриф.\n\n1 бонус = 1 сомонӣ. Бо бонусҳо то ${b.maxSpendPercent}% ташрифро пардохт кардан мумкин аст - ба маъмур гӯед.`,
  bonusOff: "Барномаи бонусӣ ҳоло амал намекунад.",
  offersTitle: "Аксияҳои салон:",
  offerLine: (o) => `${o.label} - ${o.title}${o.description ? `\n${o.description}` : ""}\nто ${o.until}${o.code ? ` · промокод ${o.code}` : ""}`,
  noOffers: "Ҳоло аксия нест - баъдтар нигаред ✦",
  cancelAsk: "Ин сабтро бекор кунем?",
  yesCancel: "Ҳа, бекор кардан",
  no: "Не",
  cancelled: "Сабт бекор карда шуд. Шуморо дар рӯзи дигар мунтазирем ✦",
  cancelFailed: "Бекор кардан нашуд",
  cantMove: "Ин сабтро гузаронидан мумкин нест - ба мо нависед.",
  moveTitle: (service, master) => `Гузаронидан: ${service}, усто ${master}.\nРӯзи навро интихоб кунед:`,
  pickNewDay: "Рӯзи навро интихоб кунед:",
  moved: (s) => `Гузаронидем ✦\n${s.service}\n${s.when}\nУсто: ${s.master}`,
  pricesTitle: "Нархҳо, сомонӣ:",
  master: "Усто",
  phone: "Телефон",
  staffOk: "Тайёр: ин чат огоҳиҳои ресепшенро дар бораи сабтҳои нав, бекоркунӣ ва гузаронидан мегирад.",
  staffBad: "Рамз мувофиқ нест. Рамзи навро дар CMS → Интеграции гиред.",
};

const en: BotTexts = {
  book: "✦ Book",
  my: "My bookings",
  prices: "Prices",
  contacts: "Contacts & address",
  language: "🌐 Язык · Забон · Language",
  backToMenu: "← Menu",
  back: "← Back",
  help: "How can I help?",
  startOver: "Let's start over.",
  welcome: (name) =>
    `Hello${name ? `, ${name}` : ""}! ✦\nThis is Mavzunai Jovid - Gallery of Beauty MJ, a beauty salon and wedding hall in Dushanbe.\n\nHere you can book a master and see or reschedule your bookings.`,
  onlyButtons: "I understand the buttons below ✦ If you need a person, message us on WhatsApp or give us a call.",
  chooseLanguage: "Choose a language:",
  languageSet: "Done - I'll speak English now ✦",
  whatToDo: "What would you like?",
  unavailable: "This service can't be booked right now.",
  whichMaster: (svc, price, min) => `${svc} · ${price} · ${min} min\nWhich master?`,
  anyMaster: "Any master",
  anyFreeMaster: "any available master",
  pickDayOff: "Choose a day (closed on Mondays):",
  pickDay: "Choose a day:",
  otherDays: "Other days:",
  waitAsk: "We can put you on the waitlist: if someone cancels on this day, the bot will send you the free time straight away.",
  waitBtn: "🔔 Let me know if a time opens up",
  waitJoined: (day) => `Done! You're on the waitlist for ${day}. As soon as a time opens up we'll message you and hold it for you for 30 minutes.`,
  waitAlready: "You're already on the waitlist for this day - we'll message you when a time opens up.",
  waitOffered: "Good news: a suitable time is already free! We're sending you a link now - please confirm within 30 minutes.",
  noTimeThatDay: (day) => `${day} - no free time. Choose another day:`,
  freeTimes: (day) => `Free times, ${day}:`,
  otherDay: "← Another day",
  check: (s) => `Please check:\n\n${s.service}\n${s.when}\nMaster: ${s.master}\nPrice: ${s.price}\n\nName: ${s.name}\nPhone: ${s.phone}`,
  confirm: "✓ Book",
  otherTime: "Another time",
  cancelFlow: "Cancel",
  askPhone: "Please share your phone number - with the button below or as a message (e.g. 98 103 11 11).",
  sharePhone: "📱 Share my number",
  badPhone: "I couldn't read that number. Please send 9 digits, e.g. 98 103 11 11.",
  thanksKnown: (name) => `Thank you, ${name}! I know you ✦`,
  thanks: "Thank you!",
  noBookingsForPhone: "No bookings for this number yet.",
  askName: "What's your name?",
  nameAgain: "Please write your name.",
  noUpcoming: "You have no upcoming bookings.",
  booking: (b) => `${b.service}\n${b.when} · with ${b.master}\n${b.confirmed ? "Confirmed ✓" : "Awaiting confirmation"}`,
  move: "Reschedule",
  cancel: "Cancel",
  anythingElse: "Anything else?",
  booked: (s) => `You're booked ✦\n\n${s.service}\n${s.when}\nMaster: ${s.master}\n\nOur receptionist will confirm it. We'll remind you a day and 2 hours before your visit.`,
  bookedDeposit: (s) => `The time is yours ✦\n\n${s.service}\n${s.when}\nMaster: ${s.master}`,
  depositLink: (sum, time, url) => `This service needs a prepayment of ${sum}. Please pay by ${time}, otherwise the time will be released:\n${url}`,
  payDeposit: (sum) => `💳 Pay the ${sum} prepayment`,
  bonusBtn: "🎁 Points",
  offersBtn: "✦ Offers",
  bonusInfo: (b) =>
    `You have ${b.balance} points ✦\n${b.tier} level - ${b.percent}% back in points on every visit.\n\n1 point = 1 somoni. Points can pay for up to ${b.maxSpendPercent}% of a visit - just tell reception.`,
  bonusOff: "The bonus program is paused right now.",
  offersTitle: "Our offers:",
  offerLine: (o) => `${o.label} - ${o.title}${o.description ? `\n${o.description}` : ""}\nuntil ${o.until}${o.code ? ` · promo code ${o.code}` : ""}`,
  noOffers: "No offers right now - check back soon ✦",
  cancelAsk: "Cancel this booking?",
  yesCancel: "Yes, cancel",
  no: "No",
  cancelled: "Booking cancelled. We'd love to see you another day ✦",
  cancelFailed: "Couldn't cancel",
  cantMove: "This booking can't be moved - please message us.",
  moveTitle: (service, master) => `Rescheduling: ${service} with ${master}.\nChoose a new day:`,
  pickNewDay: "Choose a new day:",
  moved: (s) => `Rescheduled ✦\n${s.service}\n${s.when}\nMaster: ${s.master}`,
  pricesTitle: "Prices, TJS:",
  master: "Master",
  phone: "Phone",
  staffOk: "Done: this chat will receive reception alerts about new bookings, cancellations and changes.",
  staffBad: "That code didn't work. Take the current code from CMS → Интеграции.",
};

const TEXTS: Record<Lang, BotTexts> = { ru, tg, en };
export const botTexts = (lang: Lang) => TEXTS[lang];
